/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-1-gda8409a+da8409a60d4fcb997a85ffd2c672744b7f600cec

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x000001A1,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1008_manufacturerDeviceName = {'T', 'e', 's', 't', '_', 'S', 'l', 'a', 'v', 'e', 0},
    .x1009_manufacturerHardwareVersion = {'V', '0', '.', '0', '.', '0', 0},
    .x100A_manufacturerSoftwareVersion = {'V', '0', '.', '0', '.', '0', 0},
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0001,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x000107D0, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x0000013B,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1029_errorBehaviorObject_sub0 = 0x02,
    .x1029_errorBehaviorObject = {0x00, 0x01},
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x00000200,
        .transmissionType = 0xFF,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x60110030,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0x40000180,
        .transmissionType = 0xFF,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x60100030,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1002_manufacturerStatusRegister = 0x00000000,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x1F80_NMTStartup = 0x00000000,
    .x2001_inputAdjustment_sub0 = 0x03,
    .x2001_inputAdjustment = {0x0A, 0x32, 0x00},
    .x2002_outputAdjustment_sub0 = 0x03,
    .x2002_outputAdjustment = {0x00000000, 0x00000000, 0x00000000},
    .x2010_inputClamp_sub0 = 0x02,
    .x2010_inputClamp = {0x00000000, 0x00000000},
    .x2011_outputClamp_sub0 = 0x01,
    .x2011_outputClamp = {0x00000000},
    .x6000_supportedVirtualDeviceTypes_sub0 = 0x02,
    .x6000_supportedVirtualDeviceTypes = {0x0200, 0x0300},
    .x6001_liftNumber = 0x00,
    .x6002_floorNumber = 0x00,
    .x6003_carDoorNumber = 0x00,
    .x6008_specificationVersion = 0x1023,
    .x6010_virtualInputMapping = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6011_virtualOutputMapping = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
    .x6089_CMStatusword_sub0 = 0x01,
    .x6089_CMStatusword = {0xFF000000},
    .x608A_CM_SIUnitAndPrefix_sub0 = 0x01,
    .x608B_CM_DataPointConfiguration_sub0 = 0x03,
    .x608B_CM_DataPointConfiguration = {0x0000, 0x0000, 0x0000}
};

OD_ATTR_EEPROM OD_EEPROM_t OD_EEPROM = {
    .x6009_certificationLabel_sub0 = 0x01,
    .x6009_certificationLabel = {{'0', 0, 0, 0, 0, 0, 0, 0, 0}},
    .x6082_CM_Mode_sub0 = 0x01,
    .x6082_CM_Mode = {0xFF},
    .x6100_inputGroup1_sub0 = 0x08,
    .x6100_inputGroup1 = {{0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x01, 0x00, 0x00, 0x00, 0x00, 0x00}},
    .x6120_inputParameter1Group1_sub0 = 0x08,
    .x6120_inputParameter1Group1 = {0xFFFF0001, 0xFFFF0001, 0xFFFF0001, 0xFFFF0001, 0xFFFF0001, 0xFFFF0001, 0xFFFF0001, 0xFFFF0001},
    .x6140_inputParameter2Group1_sub0 = 0x08,
    .x6140_inputParameter2Group1 = {0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF},
    .x6160_inputParameter3Group1_sub0 = 0x08,
    .x6160_inputParameter3Group1 = {0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF},
    .x6200_outputGroup1_sub0 = 0x08,
    .x6200_outputGroup1 = {{0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}},
    .x6220_outputParameter1Group1_sub0 = 0x08,
    .x6220_outputParameter1Group1 = {0x00FFFF01, 0x00FFFF01, 0x00FFFF01, 0x00FFFF01, 0x00FFFF01, 0x00FFFF01, 0x00FFFF01, 0x00FFFF01},
    .x6240_outputParameter2Group1_sub0 = 0x08,
    .x6240_outputParameter2Group1 = {0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF},
    .x6260_outputParameter3Group1_sub0 = 0x08,
    .x6260_outputParameter3Group1 = {0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF, 0xFFFF7FFF},
    .x62B0_textPositionIndication_sub0 = 0x01,
    .x62B0_textPositionIndication = {{'0', 0}},
    .x6530_floorAndMessageDisplayCar_sub0 = 0x04,
    .x6530_floorAndMessageDisplayCar = {0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x6531_floorAndMessageDisplayShaft_sub0 = 0x04,
    .x6531_floorAndMessageDisplayShaft = {0x00000000, 0x00000000, 0x00000000, 0x00000000}
};

OD_ATTR_ROM OD_ROM_t OD_ROM = {
    .x6080_CM_IdentificationLocation_sub0 = 0x01,
    .x6080_CM_IdentificationLocation = {0x00FF00FF},
    .x6081_CM_FunctionID_sub0 = 0x01,
    .x6081_CM_FunctionID = {0xFFF60020}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1002_manufacturerStatusRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_array_t o_1029_errorBehaviorObject;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_var_t o_1F80_NMTStartup;
    OD_obj_var_t o_1F89_bootTime;
    OD_obj_array_t o_2001_inputAdjustment;
    OD_obj_array_t o_2002_outputAdjustment;
    OD_obj_array_t o_2010_inputClamp;
    OD_obj_array_t o_2011_outputClamp;
    OD_obj_array_t o_6000_supportedVirtualDeviceTypes;
    OD_obj_var_t o_6001_liftNumber;
    OD_obj_var_t o_6002_floorNumber;
    OD_obj_var_t o_6003_carDoorNumber;
    OD_obj_var_t o_6008_specificationVersion;
    OD_obj_array_t o_6009_certificationLabel;
    OD_obj_var_t o_6010_virtualInputMapping;
    OD_obj_var_t o_6011_virtualOutputMapping;
    OD_obj_array_t o_6080_CM_IdentificationLocation;
    OD_obj_array_t o_6081_CM_FunctionID;
    OD_obj_array_t o_6082_CM_Mode;
    OD_obj_array_t o_6089_CMStatusword;
    OD_obj_array_t o_608A_CM_SIUnitAndPrefix;
    OD_obj_array_t o_608B_CM_DataPointConfiguration;
    OD_obj_array_t o_6100_inputGroup1;
    OD_obj_array_t o_6120_inputParameter1Group1;
    OD_obj_array_t o_6140_inputParameter2Group1;
    OD_obj_array_t o_6160_inputParameter3Group1;
    OD_obj_array_t o_6200_outputGroup1;
    OD_obj_array_t o_6220_outputParameter1Group1;
    OD_obj_array_t o_6240_outputParameter2Group1;
    OD_obj_array_t o_6260_outputParameter3Group1;
    OD_obj_array_t o_62B0_textPositionIndication;
    OD_obj_array_t o_6530_floorAndMessageDisplayCar;
    OD_obj_array_t o_6531_floorAndMessageDisplayShaft;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1002_manufacturerStatusRegister = {
        .dataOrig = &OD_RAM.x1002_manufacturerStatusRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1008_manufacturerDeviceName = {
        .dataOrig = &OD_PERSIST_COMM.x1008_manufacturerDeviceName[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 10
    },
    .o_1009_manufacturerHardwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x1009_manufacturerHardwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 6
    },
    .o_100A_manufacturerSoftwareVersion = {
        .dataOrig = &OD_PERSIST_COMM.x100A_manufacturerSoftwareVersion[0],
        .attribute = ODA_SDO_R | ODA_STR,
        .dataLength = 6
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1029_errorBehaviorObject = {
        .dataOrig0 = &OD_PERSIST_COMM.x1029_errorBehaviorObject_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1029_errorBehaviorObject[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1F80_NMTStartup = {
        .dataOrig = &OD_RAM.x1F80_NMTStartup,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1F89_bootTime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_2001_inputAdjustment = {
        .dataOrig0 = &OD_RAM.x2001_inputAdjustment_sub0,
        .dataOrig = &OD_RAM.x2001_inputAdjustment[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_2002_outputAdjustment = {
        .dataOrig0 = &OD_RAM.x2002_outputAdjustment_sub0,
        .dataOrig = &OD_RAM.x2002_outputAdjustment[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2010_inputClamp = {
        .dataOrig0 = &OD_RAM.x2010_inputClamp_sub0,
        .dataOrig = &OD_RAM.x2010_inputClamp[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_2011_outputClamp = {
        .dataOrig0 = &OD_RAM.x2011_outputClamp_sub0,
        .dataOrig = &OD_RAM.x2011_outputClamp[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6000_supportedVirtualDeviceTypes = {
        .dataOrig0 = &OD_RAM.x6000_supportedVirtualDeviceTypes_sub0,
        .dataOrig = &OD_RAM.x6000_supportedVirtualDeviceTypes[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6001_liftNumber = {
        .dataOrig = &OD_RAM.x6001_liftNumber,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6002_floorNumber = {
        .dataOrig = &OD_RAM.x6002_floorNumber,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6003_carDoorNumber = {
        .dataOrig = &OD_RAM.x6003_carDoorNumber,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_6008_specificationVersion = {
        .dataOrig = &OD_RAM.x6008_specificationVersion,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 2
    },
    .o_6009_certificationLabel = {
        .dataOrig0 = &OD_EEPROM.x6009_certificationLabel_sub0,
        .dataOrig = &OD_EEPROM.x6009_certificationLabel[0][0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_STR,
        .dataElementLength = 8,
        .dataElementSizeof = sizeof(char[9])
    },
    .o_6010_virtualInputMapping = {
        .dataOrig = &OD_RAM.x6010_virtualInputMapping[0],
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 6
    },
    .o_6011_virtualOutputMapping = {
        .dataOrig = &OD_RAM.x6011_virtualOutputMapping[0],
        .attribute = ODA_SDO_RW | ODA_TRPDO,
        .dataLength = 6
    },
    .o_6080_CM_IdentificationLocation = {
        .dataOrig0 = &OD_ROM.x6080_CM_IdentificationLocation_sub0,
        .dataOrig = &OD_ROM.x6080_CM_IdentificationLocation[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6081_CM_FunctionID = {
        .dataOrig0 = &OD_ROM.x6081_CM_FunctionID_sub0,
        .dataOrig = &OD_ROM.x6081_CM_FunctionID[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6082_CM_Mode = {
        .dataOrig0 = &OD_EEPROM.x6082_CM_Mode_sub0,
        .dataOrig = &OD_EEPROM.x6082_CM_Mode[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(uint8_t)
    },
    .o_6089_CMStatusword = {
        .dataOrig0 = &OD_RAM.x6089_CMStatusword_sub0,
        .dataOrig = &OD_RAM.x6089_CMStatusword[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_608A_CM_SIUnitAndPrefix = {
        .dataOrig0 = &OD_RAM.x608A_CM_SIUnitAndPrefix_sub0,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_608B_CM_DataPointConfiguration = {
        .dataOrig0 = &OD_RAM.x608B_CM_DataPointConfiguration_sub0,
        .dataOrig = &OD_RAM.x608B_CM_DataPointConfiguration[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 2,
        .dataElementSizeof = sizeof(uint16_t)
    },
    .o_6100_inputGroup1 = {
        .dataOrig0 = &OD_EEPROM.x6100_inputGroup1_sub0,
        .dataOrig = &OD_EEPROM.x6100_inputGroup1[0][0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 6,
        .dataElementSizeof = sizeof(uint8_t[6])
    },
    .o_6120_inputParameter1Group1 = {
        .dataOrig0 = &OD_EEPROM.x6120_inputParameter1Group1_sub0,
        .dataOrig = &OD_EEPROM.x6120_inputParameter1Group1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6140_inputParameter2Group1 = {
        .dataOrig0 = &OD_EEPROM.x6140_inputParameter2Group1_sub0,
        .dataOrig = &OD_EEPROM.x6140_inputParameter2Group1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6160_inputParameter3Group1 = {
        .dataOrig0 = &OD_EEPROM.x6160_inputParameter3Group1_sub0,
        .dataOrig = &OD_EEPROM.x6160_inputParameter3Group1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6200_outputGroup1 = {
        .dataOrig0 = &OD_EEPROM.x6200_outputGroup1_sub0,
        .dataOrig = &OD_EEPROM.x6200_outputGroup1[0][0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW,
        .dataElementLength = 6,
        .dataElementSizeof = sizeof(uint8_t[6])
    },
    .o_6220_outputParameter1Group1 = {
        .dataOrig0 = &OD_EEPROM.x6220_outputParameter1Group1_sub0,
        .dataOrig = &OD_EEPROM.x6220_outputParameter1Group1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6240_outputParameter2Group1 = {
        .dataOrig0 = &OD_EEPROM.x6240_outputParameter2Group1_sub0,
        .dataOrig = &OD_EEPROM.x6240_outputParameter2Group1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6260_outputParameter3Group1 = {
        .dataOrig0 = &OD_EEPROM.x6260_outputParameter3Group1_sub0,
        .dataOrig = &OD_EEPROM.x6260_outputParameter3Group1[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_62B0_textPositionIndication = {
        .dataOrig0 = &OD_EEPROM.x62B0_textPositionIndication_sub0,
        .dataOrig = &OD_EEPROM.x62B0_textPositionIndication[0][0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_STR,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(char[2])
    },
    .o_6530_floorAndMessageDisplayCar = {
        .dataOrig0 = &OD_EEPROM.x6530_floorAndMessageDisplayCar_sub0,
        .dataOrig = &OD_EEPROM.x6530_floorAndMessageDisplayCar[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6531_floorAndMessageDisplayShaft = {
        .dataOrig0 = &OD_EEPROM.x6531_floorAndMessageDisplayShaft_sub0,
        .dataOrig = &OD_EEPROM.x6531_floorAndMessageDisplayShaft[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1002, 0x01, ODT_VAR, &ODObjs.o_1002_manufacturerStatusRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1008, 0x01, ODT_VAR, &ODObjs.o_1008_manufacturerDeviceName, NULL},
    {0x1009, 0x01, ODT_VAR, &ODObjs.o_1009_manufacturerHardwareVersion, NULL},
    {0x100A, 0x01, ODT_VAR, &ODObjs.o_100A_manufacturerSoftwareVersion, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1029, 0x03, ODT_ARR, &ODObjs.o_1029_errorBehaviorObject, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1F80, 0x01, ODT_VAR, &ODObjs.o_1F80_NMTStartup, NULL},
    {0x1F89, 0x01, ODT_VAR, &ODObjs.o_1F89_bootTime, NULL},
    {0x2001, 0x04, ODT_ARR, &ODObjs.o_2001_inputAdjustment, NULL},
    {0x2002, 0x04, ODT_ARR, &ODObjs.o_2002_outputAdjustment, NULL},
    {0x2010, 0x03, ODT_ARR, &ODObjs.o_2010_inputClamp, NULL},
    {0x2011, 0x02, ODT_ARR, &ODObjs.o_2011_outputClamp, NULL},
    {0x6000, 0x03, ODT_ARR, &ODObjs.o_6000_supportedVirtualDeviceTypes, NULL},
    {0x6001, 0x01, ODT_VAR, &ODObjs.o_6001_liftNumber, NULL},
    {0x6002, 0x01, ODT_VAR, &ODObjs.o_6002_floorNumber, NULL},
    {0x6003, 0x01, ODT_VAR, &ODObjs.o_6003_carDoorNumber, NULL},
    {0x6008, 0x01, ODT_VAR, &ODObjs.o_6008_specificationVersion, NULL},
    {0x6009, 0x02, ODT_ARR, &ODObjs.o_6009_certificationLabel, NULL},
    {0x6010, 0x01, ODT_VAR, &ODObjs.o_6010_virtualInputMapping, NULL},
    {0x6011, 0x01, ODT_VAR, &ODObjs.o_6011_virtualOutputMapping, NULL},
    {0x6080, 0x02, ODT_ARR, &ODObjs.o_6080_CM_IdentificationLocation, NULL},
    {0x6081, 0x02, ODT_ARR, &ODObjs.o_6081_CM_FunctionID, NULL},
    {0x6082, 0x02, ODT_ARR, &ODObjs.o_6082_CM_Mode, NULL},
    {0x6089, 0x02, ODT_ARR, &ODObjs.o_6089_CMStatusword, NULL},
    {0x608A, 0x02, ODT_ARR, &ODObjs.o_608A_CM_SIUnitAndPrefix, NULL},
    {0x608B, 0x04, ODT_ARR, &ODObjs.o_608B_CM_DataPointConfiguration, NULL},
    {0x6100, 0x09, ODT_ARR, &ODObjs.o_6100_inputGroup1, NULL},
    {0x6120, 0x09, ODT_ARR, &ODObjs.o_6120_inputParameter1Group1, NULL},
    {0x6140, 0x09, ODT_ARR, &ODObjs.o_6140_inputParameter2Group1, NULL},
    {0x6160, 0x09, ODT_ARR, &ODObjs.o_6160_inputParameter3Group1, NULL},
    {0x6200, 0x09, ODT_ARR, &ODObjs.o_6200_outputGroup1, NULL},
    {0x6220, 0x09, ODT_ARR, &ODObjs.o_6220_outputParameter1Group1, NULL},
    {0x6240, 0x09, ODT_ARR, &ODObjs.o_6240_outputParameter2Group1, NULL},
    {0x6260, 0x09, ODT_ARR, &ODObjs.o_6260_outputParameter3Group1, NULL},
    {0x62B0, 0x02, ODT_ARR, &ODObjs.o_62B0_textPositionIndication, NULL},
    {0x6530, 0x05, ODT_ARR, &ODObjs.o_6530_floorAndMessageDisplayCar, NULL},
    {0x6531, 0x05, ODT_ARR, &ODObjs.o_6531_floorAndMessageDisplayShaft, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
