dependency:
# for macos
#	cd build && cmake ..
# --graphviz=graph.dot && dot -Tpng graph.dot -o graphImage.png

# for windows
	cd build && cmake -S .. -B . -G "Ninja"

prepare:
	rm -rf build
	mkdir build
