/**
  ******************************************************************************
  * @file      stm32_interrupt_handlers.c
  * @author    Generated by GitHub Copilot
  * @brief     Custom interrupt handlers for STM32C031C6 debugging
  ******************************************************************************
  */

#include "stm32c0xx.h"

/**
 * @brief  HardFault handler with detailed debugging information
 *         This handler will be called instead of the weak default handler
 *         Adapted for Cortex-M0+ (STM32C031C6) - limited fault registers
 */
void HardFault_Handler(void)
{
    // Cortex-M0+ has limited fault registers compared to M3/M4/M7
    // Only basic fault information is available
    volatile uint32_t lr_value;             // Link Register value
    volatile uint32_t pc_value = 0;         // Program Counter value
    volatile uint32_t psr_value = 0;        // Program Status Register value
    volatile uint32_t r0_value = 0;         // R0 register value
    volatile uint32_t r1_value = 0;         // R1 register value
    volatile uint32_t r2_value = 0;         // R2 register value
    volatile uint32_t r3_value = 0;         // R3 register value
    
    // Get Link Register (contains return address)
    __asm volatile ("mov %0, lr" : "=r" (lr_value));
    
    // Get values from the stack frame
    volatile uint32_t *stack_ptr;
    __asm volatile ("mrs %0, msp" : "=r" (stack_ptr));
    
    // Stack frame contains: R0, R1, R2, R3, R12, LR, PC, PSR
    if (stack_ptr != NULL) {
        r0_value = stack_ptr[0];   // R0 register at fault
        r1_value = stack_ptr[1];   // R1 register at fault
        r2_value = stack_ptr[2];   // R2 register at fault
        r3_value = stack_ptr[3];   // R3 register at fault
        pc_value = stack_ptr[6];   // Program Counter at fault
        psr_value = stack_ptr[7];  // Program Status Register at fault
    }
    
    // Set breakpoints here to examine fault details in debugger
    (void)lr_value;
    (void)pc_value;
    (void)psr_value;
    (void)r0_value;
    (void)r1_value;
    (void)r2_value;
    (void)r3_value;
    
    // Infinite loop to halt execution for debugging
    while (1)
    {
        // You can set a breakpoint here to examine variables
        __NOP();
    }
}

/**
 * @brief  Enhanced Default handler with IRQ number detection
 */
void Default_Handler(void)
{
    // Get the active IRQ number to help with debugging
    volatile uint32_t active_irq = __get_IPSR() & 0x1FF;
    
    // Set breakpoint here - you can examine active_irq in debugger
    (void)active_irq;
    
    while (1)
    {
        __NOP();
    }
}
